// <auto-generated />
using ChangeManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ChangeManagement.Api.Migrations
{
    [DbContext(typeof(ChangeManagementDbContext))]
    [Migration("20260219010000_MP08E_FixChangeApprover")]
    partial class MP08EFixChangeApprover
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
